[tool.pyright]
include = ["backend/app"]
pythonVersion = "3.14"
pythonPlatform = "Linux"
typeCheckingMode = "basic"
reportMissingImports = false
reportMissingTypeStubs = false
reportAttributeAccessIssue = false
useLibraryCodeForTypes = true